name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-posts-uservice:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Print docker-compose version
        run: docker compose --version
      - name: Run tests via docker
        working-directory: ./server/services/posts-uservice
        run: make docker-test-debug DOCKER_COMPOSE="docker compose"
